export const projects = [
  {
    slug: 'omron',
    title: 'OMRON',
    category: 'Website Rewamp',
    description: 'An AI-powered platform designed to automate and personalise client communication.',
    role: 'Design',
    year: '2025',
    placeholderColor: '#1a1a2e',
    tags: ['Website', 'UI/UX', '2025'],
  },
  {
    slug: 'akoi',
    title: 'AKOI',
    category: 'Web Design',
    description: 'Portfolio compilation and creation of the pages',
    role: 'In-House Designer',
    year: '2025',
    placeholderColor: '#1c2b1e',
    tags: ['Web Design', 'Branding', '2025'],
  },
  {
    slug: 'tattoo-studio',
    title: 'Tattoo Studio',
    category: 'Web Design',
    description: 'Portfolio-first website for a tattoo studio in BTM Layout, Bengaluru.',
    role: 'Freelance Designer',
    year: '2026',
    placeholderColor: '#2b1c2b',
    tags: ['Web Design', 'Freelance', '2026'],
  },
]